# Description
# ===========
# This playbook creates below Azure resources:
# - Azure container Instance
# 
# This playbook do:
# - git clone a hello world app.
# - build docker image of the app.
# - push the image to existing Azure Container Registry.
# - create Azure Container Instance, with image in Azure Container Registry pushed before.
#
- name: demo Build/Push docker image to Container Registry, Create Container Instance
  hosts: localhost
  vars:
    resource_group: ansiblefest-yungez1
    location: eastus
    registry_name: acrfest1
    image_name: aci-helloworld
    http_port: 80
    repo_url: "https://github.com/Azure-Samples/aci-helloworld.git"
    workspace: ~/src/aci-helloworld

  roles:
    - Azure.azure_preview_modules

  tasks:
    - name: Get existing Azure Container Registry facts
      azure_rm_containerregistry_facts:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name }}"
        retrieve_credentials: true
      register: acr_result

    - name: dump out
      debug:
        var: acr_result

    - name: Git Clone
      git:
        repo: "{{ repo_url }}"
        dest: "{{ workspace }}"

    - name: Login docker registry
      docker_login:
        registry: "{{ registry_name }}.azurecr.io"
        username: "{{ registry_name }}"
        password: "{{ acr_result.registries[0].credentials.password }}"

    - name: Docker Build and Push
      docker_image:
        path: "{{ workspace }}"
        name: "{{ registry_name }}.azurecr.io/{{ image_name }}"
        push: yes

    - name: Create Azure Container Instance
      azure_rm_containerinstance:
        resource_group: "{{ resource_group }}"
        name: "{{ image_name }}"
        ip_address: public
        ports:
          - "{{ http_port }}"
        registry_login_server: "{{ registry_name }}.azurecr.io"
        registry_username: "{{ registry_name }}"
        registry_password: "{{ acr_result.registries[0].credentials.password }}"
        containers:
          - name: "{{ image_name }}"
            ports:
              - "{{ http_port }}"
            image: "{{ registry_name }}.azurecr.io/{{ image_name }}"