# Description
# ===========
# This playbook creates below Azure resources:
# - Azure container Registry
# 
- name: demo - create Azure Container Registry
  hosts: localhost
  vars:
    resource_group: ansiblefest-yungez1
    location: eastus
    registry_name: acr0925
  tasks:

    - name: Create a resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"

    - name: Create Azure Container Registry
      azure_rm_containerregistry:
        resource_group: "{{ resource_group }}"
        name: "{{ registry_name }}"
        admin_user_enabled: True
        sku: Standard


