# Description
# ===========
# This playbook create an Azure Linux Web app with Java container Tomcat 8.5.
#
- hosts: localhost
  connection: local
  vars:
    resource_group_name: ansiblefest-yungez-webapp
    plan_resource_group: ansiblewebapp-plan
    app_name: webapp09201
    location: eastus
    linux_plan_name: linux_appplan1

  # roles:
  #   - Azure.azure_preview_modules
  
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
        name: "{{ resource_group_name }}"
        location: "{{ location }}"

  - name: Create resource group for app service plan
    azure_rm_resourcegroup:
        name: "{{ plan_resource_group }}"
        location: "{{ location }}"

  - name: Create a linux web app Java framework and Tomcat
    azure_rm_webapp:
        resource_group: "{{ resource_group_name }}"
        name: "{{ app_name }}"
        plan:
          resource_group: "{{ plan_resource_group }}"
          name: "{{ linux_plan_name }}"
          is_linux: true
          sku: S1
          number_of_workers: 1
        app_settings:
          testkey: "testvalue"
        frameworks:
          - name: java
            version: "8"
            settings:
              java_container: "Tomcat"
              java_container_version: "8.5"
  
  - name: Get web app facts
    azure_rm_webapp_facts:
      resource_group: "{{ resource_group_name }}"
      name: "{{ app_name }}"
    register: webapp